<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitf9136db24abf83d35db45e3ab47b5a5b
{
    public static $prefixLengthsPsr4 = array (
        'C' => 
        array (
            'Composer\\Installers\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Composer\\Installers\\' => 
        array (
            0 => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitf9136db24abf83d35db45e3ab47b5a5b::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitf9136db24abf83d35db45e3ab47b5a5b::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitf9136db24abf83d35db45e3ab47b5a5b::$classMap;

        }, null, ClassLoader::class);
    }
}
